- _config.yml
> add title and description

- _posts/2020-04-27-Transaction_Broker_v1.53.0.md
- _posts/2020-04-28-Control_Center_v1.41.0.md
- _posts/2020-04-28-Settings_API_v1.12.0.md
* Transaction Broker v01.53.0
* Control Center v01.41.0
* Settings API v1.12.0
> Release notes for Week 18

- _posts/2020-01-22-Reporting_API_v1.8.0.md
- _posts/2020-03-10-Reporting_API_v1.9.0.md
- _posts/2020-03-24-Reporting_API_v1.10.0.md
- _posts/2020-05-14-Reporting_API_v1.11.0.md
- _posts/2020-05-16-Control_Center_v1.42.0.md
* Control Center v1.42.0
* Rename "Reporting" to "Reporting API"
> Release notes week 20

- _posts/2020-05-18-Payment_Fusion_Gateway.md
* IIN lookup enhancements
* healthcare object in callbacks
* Save-only HPP callback
> Adds release notes for the Payment Fusion Gateway.

- _posts/2020-05-21-Transaction_Broker_v1.54.0.md
- _posts/2020-05-26-Payment_Fusion_Gateway.md
* Updated release date for TB v1.54.0 on Production.
> Gateway release notes for the week of May 26th.

- _posts/2020-05-26-Payment_Fusion_Gateway_v1.0.1.md
- _posts/2020-06-10-Payment_Fusion_Gateway_v1.0.2.md
- _posts/2020-06-10-Transaction_Broker_v1.55.0.md
Release notes for:
* Transaction Broker v1.55.0
* Gateway v1.0.2
> Release notes week 24

- _posts/2020-05-05-PFTA—Telium_v1.78.0-v.1.79.0.md
PFTA—Telium now handles timezones.
> Adds release notes for PFTA—Telium v0178 / v0179

- _posts/2020-06-15-Control_Center_v1.43.0.md
- _posts/2020-06-15-Settings_API_v1.13.0.md
Release notes for Control Center and Settings API.
> Release notes week 25

- _posts/2020-06-15-Control_Center_v1.43.0.md
Fixes the release version for v1.43.0
> Fixes the release version for v1.43.0

- _posts/2020-06-23-Transaction_Broker_v1.56.0.md
> Creates release notes for Transaction Broker v1.56.0.

- _posts/2020-06-23-Reporting_API_v1.12.0.md
> Creates release notes for Reporting API v1.12.0.

- _posts/2020-06-24-Payment_Fusion_Gateway_v1.0.3.md
> Creates release notes for Payment Fusion Gateway v1.0.3

- _posts/2020-06-23-Transaction_Broker_v1.56.0.md
> Updates the version number to v1.56.0.

- _posts/2020-06-26-Control_Center_v1.44.0.md
> Adds release note for Control Center v1.44.0.

- _posts/2020-06-26-Settings_API_v1.14.0.md
> Add release notes for Settings API v1.14.0

- _posts/2020-07-06-Payment_Fusion_Gateway_v1.0.4.md
MOTO features and recurring additions / bug fixes.
> Adds release notes for Payment Fusion Gateway v1.0.4.

- _posts/2020-07-15-Transaction_Broker_v1.57.0.md
MOTO features / infrastructure changes
> Adds release notes for Transaction Broker v1.57.0

- _posts/2020-07-22-Payment_Fusion_Gateway_v1.0.5.md
Mastercard / Discover PRA and mobile wallet.
> Adds release notes for Payment Fusion Gateway v1.0.5

- _posts/2020-07-22-Control_Center_v1.45.0.md
> Adds release notes for Control Center v1.45.0.

- _posts/2020-08-18-Control_Center_v1.46.0.md
* Transactions reporting improvements.
> Adds release notes for Control Center v1.46.0.

- _posts/2020-08-18-Reporting_API_v1.13.0.md
> Adds release notes for Reporting API v1.13.0.

- _posts/2020-08-18-Transaction_Broker_v1.58.0.md
* Performance and stability improvements.
> Adds release notes for Transaction Broker v1.58.0.

- _posts/2020-08-18-Settings_API_v1.16.0.md
* Performance and stability improvements.
> Adds release notes for Settings API v1.16.0.

- _posts/2020-08-18-Payment_Fusion_Gateway_v1.0.6.md
* Override partial authorization
* Portal UI changes
* Bug fixes
> Adds release notes for Payment Fusion Gateway v1.0.6.

- _posts/2020-08-18-Control_Center_v1.46.0.md
* Changed to "This release ..."
> Removes reference to Control Center v1.45.0 in lead.

- _posts/2020-09-04-Transaction_Broker_v1.59.0.md
* Receipts
* Partial auth improvements
* Bugs
* Documentation updates
> Creates release notes for Transaction Broker v1.59.0.

- _posts/2020-09-04-Control_Center_v1.47.0.md
* Export merchants
* Supress browser autofill
> Creates release notes for Control Center v1.47.0

- _posts/2020-09-04-Payment_Fusion_Gateway_v1.0.7.md
* Loopback (Approve All) Processor Handler
* Reporting responses
* UI updates
* Bug fixes
> Creates release notes for Payment Fusion Gateway v1.0.7

- _posts/2020-09-04-Payment_Fusion_Gateway_v1.0.7.md
* Honors partial auth setting for Healthcare, MOTO Healthcare, and MOTO
> Adds another bug fix for v1.0.7

- _posts/2020-09-15-Transaction_Broker_v1.60.0.md
* V2 Enpoints
* First / Last day of the month for Recurring start date.
* Rerversals on auth-only transactions
* POST /print_receipts
> Adds release notes for Transaction Broker v1.60.0

- _posts/2020-09-15-Transaction_Broker_v1.60.0.md
Sandbox: Thursday, October 8
Production: Thursday, October 15
> Changes the release dates for Sandbox and Production.

- _posts/2020-09-15-Transaction_Broker_v1.60.0.md
* Sandbox: Monday, October 12
* Production: Monday, October 19
> Updates deployment dates for v1.60.0

- _posts/2020-09-30-Payment_Fusion_Gateway_v1.0.8.md
* Healthcare object validation
* Bug fixes
> Adds release notes for Payment Fusion Gateway v1.0.8

- _posts/2020-10-22-Control_Center_v1.48.0.md
* PAX Terminal restart
* UI Improvements
* Bug fixes
> Adds release notes for Control Center v1.48.0

- _posts/2020-11-03-PFTA—Telium_v1.80.0-v.1.81.0.md
* TSYS / Firstdata — v1.80.0
* Chase — v1.81.0
> Adds release notes for PFTA—Telium

- _posts/2020-11-04-Transaction_Broker_2020.1.0.md
* Adds details to the terminal status.
* Adds status to a busy terminal error response.
* Fixes a void issue.
> Adds release notes for Transaction Broker 2020.1.0.

- _posts/2020-11-04-Payment_Fusion_Gateway_v1.0.9.md
* Improvements for reversals, voids, and refunds.
> Adds release notes for Payment Fusion Gateway v1.0.9

- _posts/2020-12-01-Payment_Fusion_Gateway_v1.0.10.md
- _posts/2020-12-01-Payment_Fusion_Gateway_v1.0.11.md
Release notes:
* Payment Fusion Gateway v1.10.0
* Payment Fusion Gateway v1.11.0
> Week 49: Payment Fusion Gateway

- _posts/2020-12-16-Transaction_Broker_2020.2.0.md
* Recurring: Phase 3 notes have been moved to the next release.
> Adds release notes for Transaction Broker v2020.2.0.

- _posts/2021-03-10-Payment_Fusion_Gateway_v2021.3.0.md
- _posts/2021-03-23-Payment_Fusion_Gateway_v2021.4.0.md
> Adds release notes for Payment Fusion Gateway

- _posts/2021-03-25-Payment_Fusion_Gateway_v2021.5.0.md
TODO: Finalize deployment schedule.
> Adds release notes for Payment Fusion Gateway v2021.5.0

- _posts/2021-04-19-Control_Center_v2021.4.1.md
> Adds release notes for Control Center v2021.4.1
